// YAML config generator for the Wraith launch wizard
// Produces valid YAML matching WraithV3Config schema

export interface WizardHost {
  ip: string
  name: string
  webUrl?: string
  webApp?: string
}

export interface WizardState {
  // Engagement
  engagementType: 'external' | 'internal' | 'assumed-breach'
  wanIp: string
  testerName: string
  testerRole: string
  organization: string
  infrastructure: string
  environment: string
  purpose: string
  monitoring: string

  // Target
  domain: string
  dc: string
  hosts: WizardHost[]
  domainUser: string
  domainPass: string

  // Planning
  maxRounds: number
  maxAgents: number
  concurrency: number
  objective: string

  // Attack
  randomize: boolean
  delayMin: number
  delayMax: number

  // Output
  logDir: string
  generateReport: boolean
  skipPreflight: boolean
}

export function getDefaultConfig(): WizardState {
  return {
    engagementType: 'external',
    wanIp: '10.0.0.183',
    testerName: 'Jaswanth Reddy Gorantla',
    testerRole: 'Security Researcher',
    organization: 'Self',
    infrastructure: 'self-owned homelab',
    environment: 'isolated lab with synthetic Active Directory (fake users, fake data)',
    purpose: 'Autonomous penetration testing research and SIEM/SOAR validation',
    monitoring: 'Wazuh SIEM + n8n SOAR + Grafana monitoring active',

    domain: 'YASHnet.local',
    dc: '172.16.20.5',
    hosts: [
      { ip: '172.16.20.103', name: 'Win10PC1', webUrl: 'http://10.0.0.183:8080', webApp: 'DVWA' },
      { ip: '172.16.20.104', name: 'Win11PC1' },
    ],
    domainUser: 'yash',
    domainPass: 'Password1',

    maxRounds: 15,
    maxAgents: 50,
    concurrency: 5,
    objective: 'full_assessment',

    randomize: true,
    delayMin: 2,
    delayMax: 10,

    logDir: './attack-logs',
    generateReport: true,
    skipPreflight: true,
  }
}

export function validateConfig(state: WizardState): string[] {
  const errors: string[] = []

  if (state.engagementType === 'external' && !state.wanIp.trim()) {
    errors.push('WAN IP is required for external engagements')
  }
  if (!state.testerName.trim()) errors.push('Tester name is required')
  if (!state.infrastructure.trim()) errors.push('Infrastructure description is required')
  if (!state.domain.trim() && state.engagementType !== 'external') {
    errors.push('Domain name is required for internal/assumed-breach')
  }
  if (state.hosts.length === 0 && state.engagementType !== 'external') {
    errors.push('At least one target host is required')
  }
  if (state.maxRounds < 1 || state.maxRounds > 50) {
    errors.push('Max rounds must be between 1 and 50')
  }
  if (state.maxAgents < 1 || state.maxAgents > 200) {
    errors.push('Max agents must be between 1 and 200')
  }

  return errors
}

export function generateConfigYaml(state: WizardState): string {
  const hostsYaml = state.hosts
    .map((h) => {
      let entry = `    - ip: "${h.ip}"\n      name: "${h.name}"`
      if (h.webUrl) entry += `\n      web_url: "${h.webUrl}"`
      if (h.webApp) entry += `\n      web_app: "${h.webApp}"`
      return entry
    })
    .join('\n')

  return `# Wraith v3.8.0 Configuration
# Generated by Wraith Console

engagement:
  type: ${state.engagementType}
  wan_ip: "${state.wanIp}"
  network_interface: "eth0"
  authorization:
    tester_name: "${state.testerName}"
    tester_role: "${state.testerRole}"
    organization: "${state.organization}"
    infrastructure: "${state.infrastructure}"
    environment: "${state.environment}"
    purpose: "${state.purpose}"
    monitoring: "${state.monitoring}"

target:
  domain: "${state.domain}"
  dc: "${state.dc}"
  hosts:
${hostsYaml}
  credentials:
    domain_user: "${state.domainUser}"
    domain_pass: "${state.domainPass}"

attack:
  randomize: ${state.randomize}
  delay_min_sec: ${state.delayMin}
  delay_max_sec: ${state.delayMax}

planning:
  max_rounds: ${state.maxRounds}
  max_total_agents: ${state.maxAgents}
  max_concurrent_agents: ${state.concurrency}
  objective: ${state.objective}

output:
  log_dir: "${state.logDir}"
  report: ${state.generateReport}

report:
  react_max_iterations: 3
  react_min_tool_calls: 2
`
}
